apiVersion: apps/v1
kind: Deployment
metadata:
  name: carvilla-static
  namespace: carvilla-static
spec:
  selector:
    matchLabels:
      app: carvilla-static
  template:
    metadata:
      labels:
        app: carvilla-static
    spec:
      containers:
      - name: carvilla-static
        image: saikrish12345/carvilla-static:1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80